# Generated by Django 5.1.6 on 2025-04-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="time",
        ),
        migrations.AddField(
            model_name="booking",
            name="end_time",
            field=models.TimeField(default="00:00:00"),
        ),
        migrations.AddField(
            model_name="booking",
            name="start_time",
            field=models.TimeField(default="00:00:00"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
